//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evdEn {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("evdEn.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string mainMenu {
            get {
                return ResourceManager.GetString("mainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our thanks.
        /// </summary>
        internal static string mainMenuCredits {
            get {
                return ResourceManager.GetString("mainMenuCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string mainMenuExit {
            get {
                return ResourceManager.GetString("mainMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load....
        /// </summary>
        internal static string mainMenuLoad {
            get {
                return ResourceManager.GetString("mainMenuLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        internal static string mainMenuNew {
            get {
                return ResourceManager.GetString("mainMenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        internal static string mainMenuOptions {
            get {
                return ResourceManager.GetString("mainMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievments.
        /// </summary>
        internal static string mainMenuTrophies {
            get {
                return ResourceManager.GetString("mainMenuTrophies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue?.
        /// </summary>
        internal static string msgContinue {
            get {
                return ResourceManager.GetString("msgContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit?.
        /// </summary>
        internal static string msgExitConfirm {
            get {
                return ResourceManager.GetString("msgExitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string msgGoBack {
            get {
                return ResourceManager.GetString("msgGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Game?.
        /// </summary>
        internal static string msgReturnToGame {
            get {
                return ResourceManager.GetString("msgReturnToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Music.
        /// </summary>
        internal static string optMenuMusic {
            get {
                return ResourceManager.GetString("optMenuMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string optMenuRating {
            get {
                return ResourceManager.GetString("optMenuRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Sound FX.
        /// </summary>
        internal static string optMenuSFX {
            get {
                return ResourceManager.GetString("optMenuSFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Voice.
        /// </summary>
        internal static string optMenuSpeach {
            get {
                return ResourceManager.GetString("optMenuSpeach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitles.
        /// </summary>
        internal static string optMenuSubtitles {
            get {
                return ResourceManager.GetString("optMenuSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string optMenuVolumes {
            get {
                return ResourceManager.GetString("optMenuVolumes", resourceCulture);
            }
        }
    }
}
